/*
 * This Java source file was generated by the Gradle 'init' task.
 */


import org.junit.jupiter.api.Test;
import timezone.TimezoneDatabase;
import timezone.TimezoneOffset;

import java.io.IOException;
import java.net.URISyntaxException;

class TimezoneDatabaseTest {

    @Test
    void testLoadTimezones() throws IOException, URISyntaxException {
        var db = TimezoneDatabase.instance();
        var timezones = db.getTimezonesByNames(new String[]{"CET"});
        assert !timezones.isEmpty();
    }

    @Test
    void testGetTimezoneNamesByNames() {
        var db = TimezoneDatabase.instance();
        var names = db.getTimezoneNamesByNames(new String[]{"CET", "PST"});
        assert names.size() == 4;
        assert names.contains("CET");
        assert names.contains("CEST");
        assert names.contains("PST");
        assert names.contains("PDT");
    }

    @Test
    void testGetTimezoneLikeCities_Zurich_ok() {
        var db = TimezoneDatabase.instance();
        var cities = db.getTimezoneLikeCities(new String[]{"Zurich"});
        assert cities.size() == 1;
        assert cities.getFirst().tzIdentifier().equals("Europe/Zurich");
    }
    @Test
    void testGetTimezoneLikeCities_EuropeZurich_ok() {
        var db = TimezoneDatabase.instance();
        var cities = db.getTimezoneLikeCities(new String[]{"Europe/Zurich"});
        assert cities.size() == 1;
        assert cities.getFirst().tzIdentifier().equals("Europe/Zurich");
    }

    @Test
    void testGetTimezoneByCountries_CH_US_ok() {
        var db = TimezoneDatabase.instance();
        var countries = db.getTimezoneByCountries(new String[]{"CH", "US"});
        assert countries.size() > 2;
    }

}
