/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import org.junit.jupiter.api.Test;

import cut.model.Result;

import static org.junit.jupiter.api.Assertions.assertEquals;

import java.io.IOException;
import java.net.URISyntaxException;

class ResultTest {

    @Test
    void first_row_expects31() throws URISyntaxException, IOException {
        // Arrange
        var result = new Result<String>(1, '\t');

        // Act
        result.addField("one");
        result.addField("two");
        result.addField("three");
        var shape = result.shape();

        // Assert
        assertEquals(3, shape.rows);
        assertEquals(1, shape.cols);
        
        System.out.println(result.printResult());

    }

    @Test
    void firstsecond_row_expects22() throws URISyntaxException, IOException {
        // Arrange
        var result = new Result<String>(2, '\t');

        // Act
        result.addField("one");
        result.addField("two");
        result.addField("three");
        var shape = result.shape();

        // Assert
        assertEquals(2, shape.rows);
        assertEquals(2, shape.cols);
        
        System.out.println(result.printResult());

    }

    @Test
    void first234_row_expects14() throws URISyntaxException, IOException {
        // Arrange
        var result = new Result<String>(4, '\t');

        // Act
        result.addField("one");
        result.addField("two");
        result.addField("three");
        var shape = result.shape();

        // Assert
        assertEquals(1, shape.rows);
        assertEquals(4, shape.cols);

        System.out.println(result.printResult());

    }
}
