/*
 * This Java source file was generated by the Gradle 'init' task.
 */


import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.Reader;
import java.net.URISyntaxException;
import java.net.URL;
import java.nio.file.Paths;

import dns.DnsMessage;
import dns.DnsResolver;
import dns.DnsServer;
import dns.Result;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.Test;
import picocli.CommandLine;

import static org.junit.jupiter.api.Assertions.assertTrue;

class DnsResolverTest {


    @Test
    void resolvedns_dorislorenzch_expect() throws IOException {
        //Arrange
        var classUnderTest = new DnsResolver();
        var cmd = new CommandLine(classUnderTest);
        String[] args = { "-d", "www.doris-lorenz.ch", "-vv" };

        //Act
        cmd.execute(args);
        Result<DnsMessage> result = cmd.getExecutionResult();

        //Assert
    }
    @Test
    void resolvedns_appenzelljarowade_expect() throws IOException {
        //Arrange
        var classUnderTest = new DnsResolver();
        var cmd = new CommandLine(classUnderTest);
        String[] args = { "-d", "www-appenzell-pool.enable.jarowa.de", "-vv" };

        //Act
        cmd.execute(args);
        Result<DnsMessage> result = cmd.getExecutionResult();

        //Assert
    }

    @Test
    void resolvedns_missing_expect() throws IOException {
        //Arrange
        var classUnderTest = new DnsResolver();
        var cmd = new CommandLine(classUnderTest);
        String[] args = { "-d", "dns-does-not-exists.de", "-vv" };

        //Act
        cmd.execute(args);
        Result<DnsMessage> result = cmd.getExecutionResult();

        //Assert
    }

    @Test
    void resolvedns_missingTlD_expect() throws IOException {
        //Arrange
        var classUnderTest = new DnsResolver();
        var cmd = new CommandLine(classUnderTest);
        String[] args = { "-d", "dns-does-not-exists.notld", "-vv" };

        //Act
        cmd.execute(args);
        Result<DnsMessage> result = cmd.getExecutionResult();

        //Assert
    }
}
