package cut;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import java.io.File;
import java.util.concurrent.Callable;

import picocli.CommandLine;
import picocli.CommandLine.Command;
import picocli.CommandLine.Option;
import picocli.CommandLine.Parameters;

@Command(name = "Cut", mixinStandardHelpOptions = true, version = "cut 1.0",
description = "cut out selected portions of each line of a file")
public class Cut implements Callable<Result>{

    public static void main(String[] args) {
        var cut = new Cut();
        var cmd = new CommandLine(cut);
        var exitCode = cmd.execute(args);
        Result result = cmd.getExecutionResult();
        System.exit(exitCode);
}

    @Option(names = "-b", description = "-b specifies byte positions")
    int[] bytePositions;

    @Option(names = "-c", description = "-b specifies character positions")
    int[] characterPositions;

    @Option(names = "-d", description = "-b specifies character positions")
    char delimiter;

    @Option(names = "-f", description = "-b specifies fields")
    String[] fields;

    @Option(names = {"-n"}, description = "-n Do not split multi-byte characters.")
    private boolean switchNotSplitMultiByteChars; 

    @Option(names = {"-s"}, description = "-s Suppress lines with no field delimiter characters.")
    private boolean switchSuppressLinesWithNoFieldDelimiter; 

    @Option(names = {"-w"}, description = "-w Use whitespace (spaces and tabs) as the delimiter.")
    private boolean switchUseWhiteSpaceAsDelimiter;

    @Parameters(index = "0", arity = "1..", description = "The file to calculate for.")
    private File[] files;

    @Override
    public Result call() throws Exception {
        return new Result();
    }
}