package lisp;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import java.util.concurrent.Callable;

import picocli.CommandLine;
import picocli.CommandLine.Command;
import picocli.CommandLine.Option;

@Command(name = "lisp", mixinStandardHelpOptions = true, version = "lisp 1.0", description = "This challenge is to build Your Own Lisp Interpreter")
public class Lisp implements Callable<Result> {

    public static void main(String[] args) {
        var nats = new Lisp();
        var cmd = new CommandLine(nats);
        var exitCode = cmd.execute(args);
        cmd.getExecutionResult();
        System.exit(exitCode);
    }

    @Option(names = "-s", description = "-s specifies starting a server, default = false, using cli")
    boolean server = false;

    @Option(names = "-p", description = "-p specifies the port, default 4222")
    int port = 4222;

    @Option(names = "-h", description = "-h specifies the server hostname, default localhost")
    String hostname = "localhost";

    @Option(names = "-c", description = "-c specifies the command executed")
    String command = null;

    boolean isInteractive = true;

    @Override
    public Result call() throws Exception {
        System.out.println("Lisp-cli started.");
        return new Result();
    }
}