package lisp;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import java.util.concurrent.Callable;

import lisp.parser.LispRuntime;
import picocli.CommandLine;
import picocli.CommandLine.Command;
import picocli.CommandLine.Parameters;

@Command(name = "lisp", mixinStandardHelpOptions = true, version = "lisp 1.0", description = "This challenge is to build Your Own Lisp Interpreter")
public class Lisp implements Callable<Result> {

    public static void main(String[] args) {
        var nats = new Lisp();
        var cmd = new CommandLine(nats);
        var exitCode = cmd.execute(args);
        Result result = cmd.getExecutionResult();
        if (result != null) {
            System.out.println(result.toString());
            System.exit(exitCode);
        }
    }

    @Parameters(description = "-c specifies the command executed")
    String command = null;

    boolean isInteractive = true;

    @Override
    public Result call() throws Exception {
        if (this.command != null) {
            return new Result(new LispRuntime().execute(this.command));
        } else {
            return new Result("done.");
        }
    }
}