package bot;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import java.util.concurrent.Callable;

import picocli.CommandLine;
import picocli.CommandLine.Command;
import picocli.CommandLine.Option;

@Command(name = "bot", mixinStandardHelpOptions = true, version = "bot 1.0", description = "This challenge is to build your own discort bot")
public class DiscortBot implements Callable<Result> {

    public static void main(String[] args) {
        var bot = new DiscortBot();
        var cmd = new CommandLine(bot);
        var exitCode = cmd.execute(args);
        cmd.getExecutionResult();
        System.exit(exitCode);
    }

    @Option(names = "-t", required = true, description = "-t specifies the bot token for the client")
    String token;

    @Override
    public Result call() throws Exception {
        new Bot().start(this.token);
        return new Result();
    }
}