package compress;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import java.io.File;
import java.io.Reader;

public class Compress  {

    public static void main(String[] args) {
    }

}