/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.io.IOException;
import java.net.URISyntaxException;
import java.util.Optional;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import redis.resp.RespException;
import redis.resp.RespPipelineInlineScanner;
import redis.resp.RespRequest;
import redis.resp.cache.RedisCache;
import redis.resp.commands.RespCommand;
import redis.resp.commands.RespCommandException;
import redis.resp.commands.library.CmdDecr;
import redis.resp.commands.library.CmdDecrBy;
import redis.resp.commands.library.CmdDel;
import redis.resp.commands.library.CmdEcho;
import redis.resp.commands.library.CmdExists;
import redis.resp.commands.library.CmdGet;
import redis.resp.commands.library.CmdIncr;
import redis.resp.commands.library.CmdIncrBy;
import redis.resp.commands.library.CmdLPush;
import redis.resp.commands.library.CmdPing;
import redis.resp.commands.library.CmdRPush;
import redis.resp.commands.library.CmdSet;
import redis.resp.commands.library.RespCommandLibrary;
import redis.resp.types.RespArray;
import redis.resp.types.RespBulkString;
import redis.resp.types.RespInteger;
import redis.resp.types.RespNull;
import redis.resp.types.RespSimpleString;
import redis.resp.types.RespType;

class RedisCmdTests {

    private RespBulkString bulk;
    private RespArray bulkArray;

    private RespCommandLibrary lib;
    private RedisCache cache;
    private RespCommand command;

    @BeforeEach
    void setup() {
        lib = new RespCommandLibrary();
        cache = new RedisCache();
    }

    private RespRequest getRequestFromType(RespType type) {
        var bulkArray = new RespArray(type);
        var command = new RespCommand(bulkArray);
        return new RespRequest(cache, command);
    }

    private RespRequest getRequestFromString(String str) throws RespCommandException {
        var scanner = new RespPipelineInlineScanner(str);
        var command = scanner.getCommands().get(0);
        return new RespRequest(cache, command.toCommand());
    }

    @Test
    void ping_empty_expectspong() throws URISyntaxException, IOException, RespCommandException {

        // Arrange
        var ping = new CmdPing(lib);
        var request = getRequestFromString("PING");

        // Act
        var response = ping.execute(request);
        var pong = (RespBulkString) response.values[0];

        // Assert
        assertEquals("PONG", pong.value);

    }

    @Test
    void ping_message_expectshello() throws URISyntaxException, IOException, RespCommandException {

        // Arrange
        var ping = new CmdPing(lib);
        var request = getRequestFromString("PING hello-world");

        // Act
        var response = ping.execute(request);
        var pong = (RespBulkString) response.values[0];

        // Assert
        assertEquals("hello-world", pong.value);

    }

    @Test
    void echo_message_expectsmessage() throws URISyntaxException, IOException, RespCommandException {

        // Arrange
        var ping = new CmdEcho(lib);
        var request = getRequestFromString("ECHO this-is-a-echo-test");

        // Act
        var response = ping.execute(request);
        var echo = (RespBulkString) response.values[0];

        // Assert
        assertEquals("this-is-a-echo-test", echo.value);

    }

    @Test
    void set_mykey_message_expectsOK_and_test() throws URISyntaxException, IOException, RespCommandException {

        // Arrange
        var set = new CmdSet(lib);
        var request = getRequestFromString("set mykey this-is-a-set-test");

        // Act
        var response = set.execute(request);
        var responseType = (RespSimpleString) response.values[0];
        Optional<RespType> cacheObject = cache.get("mykey");

        // Assert
        assertEquals("OK", responseType.value);
        assertTrue(cacheObject.isPresent());
        assertEquals("this-is-a-set-test", cacheObject.get().value);

    }

    @Test
    void set_mykey_messagetwice_expectspong() throws URISyntaxException, IOException, RespCommandException {

        // Arrange
        var set = new CmdSet(lib);
        var request = getRequestFromString("set mykey this-is-the-first-string");
        set.execute(request);

        // Act
        var request2 = getRequestFromString("set mykey this-is-the-second-string");
        var response2 = set.execute(request2);
        var responseType2 = (RespSimpleString) response2.values[0];
        var cacheObject = cache.get("mykey");

        // Assert
        assertEquals("OK", responseType2.value);
        assertTrue(cacheObject.isPresent());
        assertEquals("this-is-the-second-string", cacheObject.get().value);

    }

    @Test
    void exists_mykey_return1() throws URISyntaxException, IOException, RespCommandException {

        // Arrange
        var set = new CmdSet(lib);
        var request = getRequestFromString("set mykey this-is-the-first-string");
        set.execute(request);

        // Act
        var set2 = new CmdExists(lib);
        var request2 = getRequestFromString("exists mykey");
        var response2 = set2.execute(request2);
        var responseType2 = (RespInteger) response2.values[0];

        // Assert
        assertEquals(1, responseType2.value);

    }

    @Test
    void exists_mykey123_return2() throws URISyntaxException, IOException, RespCommandException {

        // Arrange
        var set = new CmdSet(lib);
        var request1 = getRequestFromString("set mykey1 this-is-the-first-string");
        var request2 = getRequestFromString("set mykey2 this-is-the-first-string");
        var request3 = getRequestFromString("set mykey3notfound this-is-the-first-string");
        set.execute(request1);
        set.execute(request2);
        set.execute(request3);

        // Act
        var set2 = new CmdExists(lib);
        var request4 = getRequestFromString("exists mykey1  mykey2  mykey3");
        var response2 = set2.execute(request4);
        var responseType2 = (RespInteger) response2.values[0];

        // Assert
        assertEquals(2, responseType2.value);

    }

    @Test
    void del_mykey123_return2() throws URISyntaxException, IOException, RespCommandException {

        // Arrange
        var set = new CmdSet(lib);
        var request1 = getRequestFromString("set mykey1 this-is-the-first-string");
        var request2 = getRequestFromString("set mykey2 this-is-the-first-string");
        var request3 = getRequestFromString("set mykey3notfound this-is-the-first-string");
        set.execute(request1);
        set.execute(request2);
        set.execute(request3);

        // Act
        var set2 = new CmdDel(lib);
        var request4 = getRequestFromString("del mykey1  mykey2  mykey3");
        var response2 = set2.execute(request4);
        var responseType2 = (RespInteger) response2.values[0];

        // Assert
        assertEquals(2, responseType2.value);

    }

    @Test
    void del_mykey123AskAnyKey_return0() throws URISyntaxException, IOException, RespCommandException {

        // Arrange
        var set = new CmdSet(lib);
        var request1 = getRequestFromString("set mykey1 this-is-the-first-string");
        var request2 = getRequestFromString("set mykey2 this-is-the-first-string");
        var request3 = getRequestFromString("set mykey3notfound this-is-the-first-string");
        set.execute(request1);
        set.execute(request2);
        set.execute(request3);

        // Act
        var set2 = new CmdDel(lib);
        var request4 = getRequestFromString("del anykeynotfound");
        var response2 = set2.execute(request4);
        var responseType2 = (RespInteger) response2.values[0];

        // Assert
        assertEquals(0, responseType2.value);

    }

    @Test
    void set_valueEx2s_expectsOK() throws URISyntaxException, IOException, RespCommandException {

        // Arrange
        var set = new CmdSet(lib);
        var request1 = getRequestFromString("set mykey this-is-the-first-string EX 2");
        set.execute(request1);

        // Act
        var get = new CmdGet(lib);
        var request4 = getRequestFromString("get mykey");
        var response2 = get.execute(request4);
        var responseType2 = (RespType) response2.values[0];

        // Assert
        assertNotEquals(RespNull.NULL, responseType2.value);

    }

    @Test
    void set_valueEx2s_expectNullAfter3s()
            throws URISyntaxException, IOException, RespCommandException, InterruptedException {

        // Arrange
        var set = new CmdSet(lib);
        var request1 = getRequestFromString("set mykey this-is-the-first-string EX 2");
        set.execute(request1);
        Thread.sleep(2500);

        // Act
        var get = new CmdGet(lib);
        var request4 = getRequestFromString("get mykey");
        var response2 = get.execute(request4);
        var responseType2 = (RespType) response2.values[0];

        // Assert
        assertEquals(RespNull.NULL, responseType2);

    }

    @Test
    void set_valueEx2sTtlAgain_expectOkAfter2_5s()
            throws URISyntaxException, IOException, RespCommandException, InterruptedException {

        // Arrange
        var set = new CmdSet(lib);
        var request1 = getRequestFromString("set mykey this-is-the-first-string EX 2");
        set.execute(request1);
        Thread.sleep(1000);
        var request2 = getRequestFromString("set mykey this-is-the-first-string KEEPTTL");
        set.execute(request2);
        Thread.sleep(1500);

        // Act
        var get = new CmdGet(lib);
        var request4 = getRequestFromString("get mykey");
        var response2 = get.execute(request4);
        var responseType2 = (RespType) response2.values[0];

        // Assert
        assertNotEquals(RespNull.NULL, responseType2);

    }

    @Test
    void set_valueEx2sTtlAgain_expectNullAfter3_5s()
            throws URISyntaxException, IOException, RespCommandException, InterruptedException {

        // Arrange
        var set = new CmdSet(lib);
        var request1 = getRequestFromString("set mykey this-is-the-first-string EX 2");
        set.execute(request1);
        Thread.sleep(1000);
        var request2 = getRequestFromString("set mykey this-is-the-first-string KEEPTTL");
        set.execute(request2);
        Thread.sleep(2500);

        // Act
        var get = new CmdGet(lib);
        var request4 = getRequestFromString("get mykey");
        var response2 = get.execute(request4);
        var responseType2 = (RespType) response2.values[0];

        // Assert
        assertEquals(RespNull.NULL, responseType2);

    }

    @Test
    void set_RedLockAlgorithm_expectsLockNullDuring2s()
            throws URISyntaxException, IOException, RespCommandException, InterruptedException {

        // Arrange
        var set = new CmdSet(lib);
        var request1 = getRequestFromString("SET resource-name anystring NX EX 2");
        set.execute(request1);

        // Act
        var get = new CmdGet(lib);
        var request4 = getRequestFromString("get resource-name");
        var response2 = get.execute(request4);
        var responseType2 = (RespType) response2.values[0];

        var responseLock = set.execute(request1);
        var responseLockType = responseLock.values[0];

        // Assert
        assertEquals("anystring", responseType2.value);
        assertEquals(RespNull.NULL, responseLockType);

    }

    @Test
    void set_RedLockAlgorithm_expectsUnlockAfter3s()
            throws URISyntaxException, IOException, RespCommandException, InterruptedException {

        // Arrange
        var set = new CmdSet(lib);
        var request1 = getRequestFromString("SET resource-name anystring NX EX 2");
        set.execute(request1);
        Thread.currentThread().sleep(3000);

        // Act
        var responseNull = set.execute(request1);
        var responseNullType = responseNull.values[0];

        // Assert
        assertNotEquals(RespNull.NULL, responseNullType);

    }

    @Test
    void incr_startwith10_get11()
            throws URISyntaxException, IOException, RespCommandException, InterruptedException, RespException {

        // Arrange
        var set = new CmdSet(lib);
        var request1 = getRequestFromString("SET resource-name 10");
        set.execute(request1);

        // Act
        var incr = new CmdIncr(lib);
        var request2 = getRequestFromString("INCR resource-name");
        var responseIncr = incr.execute(request2);
        var responseIncrType = responseIncr.values[0];

        // Assert
        assertEquals(11L, responseIncrType.getLong());

    }

    @Test
    void incr12_startwith10_get11()
            throws URISyntaxException, IOException, RespCommandException, InterruptedException, RespException {

        // Arrange
        var set = new CmdSet(lib);
        var request1 = getRequestFromString("SET resource-name 10");
        set.execute(request1);

        // Act
        var incr = new CmdIncrBy(lib);
        var request2 = getRequestFromString("INCRBY resource-name 12");
        var responseIncr = incr.execute(request2);
        var responseIncrType = responseIncr.values[0];

        // Assert
        assertEquals(22L, responseIncrType.getLong());

    }

    @Test
    void incr1_startwithnull_get1()
            throws URISyntaxException, IOException, RespCommandException, InterruptedException, RespException {

        // Arrange

        // Act
        var incr = new CmdIncr(lib);
        var request2 = getRequestFromString("INCR resource-name");
        var responseIncr = incr.execute(request2);
        var responseIncrType = responseIncr.values[0];

        // Assert
        assertEquals(1L, responseIncrType.getLong());

    }

    @Test
    void decr_startwith10_get11()
            throws URISyntaxException, IOException, RespCommandException, InterruptedException, RespException {

        // Arrange
        var set = new CmdSet(lib);
        var request1 = getRequestFromString("SET resource-name 10");
        set.execute(request1);

        // Act
        var decr = new CmdDecr(lib);
        var request2 = getRequestFromString("DECR resource-name");
        var responseDecr = decr.execute(request2);
        var responseDecrType = responseDecr.values[0];

        // Assert
        assertEquals(9L, responseDecrType.getLong());

    }

    @Test
    void decr12_startwith10_get_2()
            throws URISyntaxException, IOException, RespCommandException, InterruptedException, RespException {

        // Arrange
        var set = new CmdSet(lib);
        var request1 = getRequestFromString("SET resource-name 10");
        set.execute(request1);

        // Act
        var decr = new CmdDecrBy(lib);
        var request2 = getRequestFromString("DECRBY resource-name 12");
        var responseDecr = decr.execute(request2);
        var responseDecrType = responseDecr.values[0];

        // Assert
        assertEquals(-2L, responseDecrType.getLong());

    }

    @Test
    void decr1_startwithnull_get_1()
            throws URISyntaxException, IOException, RespCommandException, InterruptedException, RespException {

        // Arrange

        // Act
        var decr = new CmdDecr(lib);
        var request2 = getRequestFromString("DECR resource-name");
        var responseDecr = decr.execute(request2);
        var responseDecrType = responseDecr.values[0];

        // Assert
        assertEquals(-1L, responseDecrType.getLong());

    }

    @Test
    void lpush2_startwithnull_getLen2()
            throws URISyntaxException, IOException, RespCommandException, InterruptedException, RespException {

        // Arrange

        // Act
        var lpush = new CmdLPush(lib);
        var request2 = getRequestFromString("LPUSH resource-name hello3 hello4");
        var responseLPush = lpush.execute(request2);
        var responseLPushType = (RespInteger) responseLPush.values[0];

        // Assert
        assertEquals(2L, responseLPushType.value);

    }

    @Test
    void lpush2_startwith2_getLen2()
            throws URISyntaxException, IOException, RespCommandException, InterruptedException, RespException {

        // Arrange
        var lpush = new CmdLPush(lib);
        var request = getRequestFromString("LPUSH resource-name hello3 hello4");
        var responseLPush = lpush.execute(request);

        // Act
        var request2 = getRequestFromString("LPUSH resource-name hello1 hello2");
        var responseLPush2 = lpush.execute(request2);
        var responseLPush2Type = (RespInteger) responseLPush2.values[0];

        // Assert
        assertEquals(4L, responseLPush2Type.value);

    }

    @Test
    void lpush2_startwith2_getHello2atposition1()
            throws URISyntaxException, IOException, RespCommandException, InterruptedException, RespException {

        // Arrange
        var lpush = new CmdLPush(lib);
        var request = getRequestFromString("LPUSH resource-name hello3 hello4");
        var responseLPush = lpush.execute(request);

        // Act
        var request2 = getRequestFromString("LPUSH resource-name hello1 hello2");
        var responseLPush2 = lpush.execute(request2);
        var responseLPush2Type = (RespInteger) responseLPush2.values[0];

        var get = new CmdGet(lib);
        var request3 = getRequestFromString("GET resource-name");
        var responseGet = get.execute(request3);
        var responseGetType = (RespArray) responseGet.values[0];

        // Assert
        assertEquals("hello2", responseGetType.value[1].value);

    }

    @Test
    void rpush2_startwith2_getHello2atposition1()
            throws URISyntaxException, IOException, RespCommandException, InterruptedException, RespException {

        // Arrange
        var rpush = new CmdRPush(lib);
        var request = getRequestFromString("RPUSH resource-name hello1 hello2");
        var responseRPush = rpush.execute(request);

        // Act
        var request2 = getRequestFromString("RPUSH resource-name hello3 hello4");
        var responseRPush2 = rpush.execute(request2);
        var responseRPush2Type = (RespInteger) responseRPush2.values[0];

        var get = new CmdGet(lib);
        var request3 = getRequestFromString("GET resource-name");
        var responseGet = get.execute(request3);
        var responseGetType = (RespArray) responseGet.values[0];

        // Assert
        assertEquals("hello3", responseGetType.value[2].value);

    }
}
