/*
 * This Java source file was generated by the Gradle 'init' task.
 */


import json.Json;
import org.junit.jupiter.api.Test;

class JsonTest {
    @Test void step1_empty() {
        Json classUnderTest = new Json();
    }
}
