/*
 * This Java source file was generated by the Gradle 'init' task.
 */


import org.junit.jupiter.api.Test;

import json.Json;

import static org.junit.jupiter.api.Assertions.*;

class JsonTest {
    @Test void step1_empty() {
        Json classUnderTest = new Json();
    }
}
