package mandelbrot;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import java.util.concurrent.Callable;

import picocli.CommandLine;
import picocli.CommandLine.Command;
import picocli.CommandLine.Option;

@Command(name = "mandelbrot", mixinStandardHelpOptions = true, version = "mandelbrot 1.0", description = "This challenge is to build your own application layer load balancer")
public class Mandelbrot implements Callable<Result> {

    public static void main(String[] args) {
        var mandelbrot = new Mandelbrot();
        var cmd = new CommandLine(mandelbrot);
        var exitCode = cmd.execute(args);
        cmd.getExecutionResult();
        System.exit(exitCode);
    }

    @Option(names = "-t", description = "-b specifies byte positions")
    int test = 8080;
    @Option(names = "-f", arity = "0..", description = "-b specifies byte positions")
    boolean flag = false;

    @Override
    public Result call() throws Exception {
        System.out.println("done");
        return new Result();
    }
}