package forth;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import picocli.CommandLine;
import picocli.CommandLine.Command;
import picocli.CommandLine.Option;

import java.util.concurrent.Callable;

@Command(name = "forth-repl", mixinStandardHelpOptions = true, version = "forth-repl 1.0", description = "This challenge is to build your own Forth interpreter")
public class Repl implements Callable<Result> {

    public static int _verbose = 0;

    @Option(names = "-v", description = "verbose model level 1")
    boolean verbose = false;
    @Option(names = "-vv", description = "verbose model level 2")
    boolean verbose2 = false;

    public static void main(String[] args) {
        var repl = new Repl();
        var cmd = new CommandLine(repl);
        var exitCode = cmd.execute(args);
        Result result = cmd.getExecutionResult();
        if (result != null && result.toString() != null) {
            System.exit(exitCode);
        }
    }

    public static boolean verbose() {
        return _verbose >= 1;
    }

    public static boolean verbose2() {
        return _verbose >= 2;
    }

    @Override
    public Result call() throws Exception {
        if (this.verbose) _verbose = 1;
        if (this.verbose2) _verbose = 2;
        new Repl().run();
        return new Result();
    }

    private void run() {
    }
}