/*
 * This Java source file was generated by the Gradle 'init' task.
 */


import org.junit.jupiter.api.Test;

class ForthParserTest {

    @Test void new_simpleoption_ok() {
        // Arrange
        // Action
        // Assert

    }
}
