package irc;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import java.util.concurrent.Callable;

import picocli.CommandLine;
import picocli.CommandLine.Command;
import picocli.CommandLine.Option;

@Command(name = "irc", mixinStandardHelpOptions = true, version = "irc 1.0", description = "This challenge is to an own irc client")
public class Irc implements Callable<Result> {

    public static void main(String[] args) {
        var irc = new Irc();
        var cmd = new CommandLine(irc);
        var exitCode = cmd.execute(args);
        cmd.getExecutionResult();
        System.exit(exitCode);
    }

    @Option(names = "-s", description = "-s specifies the irc server. default irc.freenode.net")
    String ircServer = "irc.freenode.net";

    @Option(names = "-p", description = "-p specifies the port on the server. default 6667")
    int port = 6667;

    @Option(names = "-n", description = "-n specifies the nick name - default CClolo8304")
    String nickName = "CClolo8304";

    @Option(names = "-c", description = "-c specifies the channel - default #CC")
    String channel = "CC";

    @Override
    public Result call() throws Exception {
        new IrcClient(this.ircServer, this.port, this.nickName, this.channel).connect();
        return new Result();
    }
}