package lb;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import java.io.File;
import java.util.concurrent.Callable;

import picocli.CommandLine;
import picocli.CommandLine.Command;

@Command(name = "lb", mixinStandardHelpOptions = true, version = "lb 1.0", description = "This challenge is to build your own application layer load balancer")
public class LoadBalancer implements Callable<Result> {

    public static void main(String[] args) {
        var compress = new LoadBalancer();
        var cmd = new CommandLine(compress);
        var exitCode = cmd.execute(args);
        Result result = cmd.getExecutionResult();
        System.exit(exitCode);
    }

    @Override
    public Result call() throws Exception {
        return new Result();
    }
}