/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

import dns.DnsServer;
import dns.HeaderFlags;
import org.junit.jupiter.api.Test;

import java.io.*;


class DnsServerTest {

    @Test
    void sendDns8888_dnsgooglecom_expect() throws IOException {
        //Arrange
        var server = "8.8.8.8";
        var port = 53;
        var dnsServer = new DnsServer(server, port, true);

        var msg = "001601000001000000000000037777770C646F7269732D6C6F72656E7A0263680000010001";
        //Act
        var received = dnsServer.sendAndReceive(msg);
        
        //Assert

        assertTrue(received.startsWith(DnsMessageTests.nospace("0016 8180 0001 0001 0000 0000 03 777777 0C 646F7269732D6C6F72656E7A 02 6368 00 0001 0001 C0 0C 00 01 0001")));
    }
    @Test
    void sendDns8888_wwwdorislorenzch_expect() throws IOException {
        //Arrange
        var dnsServer = new DnsServer(true);

        //Act
        var received = dnsServer.lookupA("www.doris-lorenz.ch");

        //Assert
        assertTrue(received.isPresent());
        assertEquals(1, received.get().getIpAddresses().size());
        assertEquals("80.74.158.130", received.get().getIpAddresses().get(0));

    }


    @Test
    void sendDns8888_jarowach_expect() throws IOException {
        //Arrange
        var dnsServer = new DnsServer(true);

        //Act
        var received = dnsServer.lookup("www.jarowa.ch", HeaderFlags.QTYPE_All);

        //Assert
        assertTrue(received.isPresent());
        assertEquals(1, received.get().getQuestionCount());
        assertEquals(5, received.get().getAuthorityCount());

    }
}
