/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import dns.DnsServer;
import dns.Name;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.Test;

import java.io.*;
import java.net.URISyntaxException;
import java.net.URL;
import java.nio.file.Paths;

import static org.junit.jupiter.api.Assertions.assertEquals;

class NameTest {

    private Reader reader;

    void ReadReader(String testfile) throws FileNotFoundException, URISyntaxException {
        URL resource = NameTest.class.getResource("tests/"+testfile);
        File file = Paths.get(resource.toURI()).toFile();
        reader = new FileReader(file);
    }

    @AfterEach
    void CloseReader() throws IOException {
        if (reader != null) {
            reader.close();
        }
    }

    @Test
    void toOctet_dnsgooglecom_expect() throws IOException {
        //Arrange
        var dnsName = "dns.google.com";
        var msg = "03646e7306676f6f676c6503636f6d00";
        //Act
        var received = Name.toOctetString(dnsName);
        
        //Assert
        assertEquals(DnsMessageTests.nospace("03 646e73 06 676f6f676c6503636f6d 00"),received);
    }
    @Test
    void toOctet_wwwdorislorenzch_expect() throws IOException {
        //Arrange
        var dnsName = "www.doris-lorenz.ch";
        var msg = "03 777777 0C 646F7269732D6C6F72656E7A 02 6368 00";
        //Act
        var received = Name.toOctetString(dnsName);

        //Assert
        assertEquals(DnsMessageTests.nospace(msg),received);
    }
    @Test
    void fromOctet_dnsgooglecom_expect() throws IOException {
        //Arrange
        var dnsName = "dns.google.com";
        var msg = "03646e7306676f6f676c6503636f6d00";
        //Act
        var received = Name.fromOctetString(msg);

        //Assert
        assertEquals("dns.google.com",received);
    }
    @Test
    void NametoOctet_dnsgooglecom_expect() throws IOException {
        //Arrange
        var dnsName = "dns.google.com";
        var msg = DnsMessageTests.nospace("03 646e73 06 676f6f676c6503636f6d 00");
        //Act
        var received = Name.fromDomainName(dnsName);

        //Assert
        assertEquals(msg, received.octetString);
        assertEquals(dnsName, received.domainName);
    }
    @Test
    void NamefromOctet_dnsgooglecom_expect() throws IOException {
        //Arrange
        var dnsName = "dns.google.com";
        var msg = DnsMessageTests.nospace("03 646e73 06 676f6f676c6503636f6d 00");
        //Act
        var received = Name.fromOctetName(msg);

        //Assert
        assertEquals(msg, received.octetString);
        assertEquals(dnsName, received.domainName);
    }
}
