/*
 * This Java source file was generated by the Gradle 'init' task.
 */


import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.Test;
import qr.EncodingMode;
import qr.QrCode;

import java.io.*;
import java.net.URISyntaxException;
import java.net.URL;
import java.nio.file.Paths;
import java.util.Scanner;

import static org.junit.jupiter.api.Assertions.assertEquals;

public class QrCodeTest {

    private Reader reader;

    void ReadReader(String testfile) throws FileNotFoundException, URISyntaxException {
        URL resource = QrCodeTest.class.getResource("tests/"+testfile);
        if (resource != null) {
            File file = Paths.get(resource.toURI()).toFile();
            reader = new FileReader(file);
        }
    }

    @AfterEach
    void CloseReader() throws IOException {
        if (reader != null) {
            reader.close();
        }
    }

    @Test
    public void detectmode_valid_ok() throws URISyntaxException, IOException {
        // Arrange
        var qr = new QrCode("HELLO CC WORLD");

        // Act
        var bits = qr.appendBits(new StringBuilder()).toString();

        // Assert
        var compare = "0010" // Mode
                +"000001110" // Character Count
                +"01100001011011110001101000101110001000101000110011101001000101001101110111110"; // Data
        assertEquals(compare, bits);

    }
}
