/*
 * This Java source file was generated by the Gradle 'init' task.
 */


import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.Test;
import qr.EncodingMode;
import qr.QrCode;
import qr.Quality;
import qr.Version;

import java.io.*;
import java.net.URISyntaxException;
import java.net.URL;
import java.nio.file.Paths;

import static org.junit.jupiter.api.Assertions.assertEquals;

public class VersionTest {

    private Reader reader;

    void ReadReader(String testfile) throws FileNotFoundException, URISyntaxException {
        URL resource = VersionTest.class.getResource("tests/"+testfile);
        if (resource != null) {
            File file = Paths.get(resource.toURI()).toFile();
            reader = new FileReader(file);
        }
    }

    @AfterEach
    void CloseReader() throws IOException {
        if (reader != null) {
            reader.close();
        }
    }

    @Test
    public void version_hellworld_ok() throws URISyntaxException, IOException {
        // Arrange
        var data = "HELLO WORLD";
        var qr = new QrCode(data, Quality.Q);

        // Act
        var version = Version.bestFixByChars(data.length(), qr.mode(), qr.quality());


        // Assert
        assertEquals(Version.version(1), version);

    }

    @Test
    public void version_helloword17_ok() throws URISyntaxException, IOException {
        // Arrange
        var data = "HELLO THERE WORLD";
        var qr = new QrCode(data, Quality.Q);

        // Act
        var version = Version.bestFixByChars(data.length(), qr.mode(), qr.quality());


        // Assert
        assertEquals(Version.version(2), version);

    }
}
