/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import static org.junit.jupiter.api.Assertions.assertEquals;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.Reader;
import java.net.URISyntaxException;
import java.net.URL;
import java.nio.file.Paths;
import java.time.Duration;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.Test;

import io.nats.client.Nats;
import io.nats.client.Options;

class NatsCliTest {

    private Reader reader;

    void ReadReader(String testfile) throws FileNotFoundException, URISyntaxException {
        URL resource = NatsCliTest.class.getResource("tests/" + testfile);
        File file = Paths.get(resource.toURI()).toFile();
        reader = new FileReader(file);
    }

    @AfterEach
    void CloseReader() throws IOException {
        if (reader != null) {
            reader.close();
        }
    }

    @Test
    void connect_simple_expectok() throws URISyntaxException, IOException, InterruptedException {
        // Arrange
        // Action
        Options o = new Options.Builder().server("nats://localhost:4222").maxReconnects(-1).traceConnection()
                .maxPingsOut(1)
                .connectionTimeout(Duration.ofSeconds(30)).build();
        var nats = Nats.connect(o);
        var info = nats.getServerInfo();

        // Assert
        assertEquals("127.0.0.1", info.getClientIp());
    }

}
